os:
  - linux
  - osx

language: cpp
compiler:
  - gcc
  - clang

before_install:
  - if [[ $TRAVIS_OS_NAME == 'linux' ]]; then sudo apt-get update -qq && sudo apt-get install -y libxerces-c-dev; fi
  - if [[ $TRAVIS_OS_NAME == 'osx' ]]; then brew update && brew install xerces-c; fi

install:
  - .travis_scripts/cmake.sh

script: cmake -G "Unix Makefiles" -Dtest=true . && make && make test

