os:
  - linux
  - osx

language: cpp
compiler:
  - gcc
  - clang

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libxerces-c-dev

install:
  - .travis_scripts/cmake.sh

script: cmake -G "Unix Makefiles" -Dtest=true . && make && make test

