macro(SET_COMPILER_FLAGS)
  if(LIBCELLML_WARNINGS_TREATED_AS_ERRORS)
    if(MSVC)
      set(CMAKE_CXX_FLAGS "/W3")
    else()
      set(CMAKE_CXX_FLAGS "-Wall -W -Werror")
    endif()
  endif()

  if (MSVC)
    set(CMAKE_CXX_FLAGS_DEBUG "${CMAKE_CXX_FLAGS_DEBUG} /MTd /EHsc")
  endif()

endmacro()

macro(DISABLE_TREATING_WARNINGS_AS_ERRORS)
  if(MSVC)
    string(REPLACE "/W3 /WX" "" CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS}")
  else()
    string(REPLACE "-Wall -W -Werror" "-w" CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS}")
  endif()
endmacro()
